adding playlist features to Youtube
LucasNry/Tune2GetherBackend pull request #10
Opened 2022-01-09 18:44 UTC by heywtl

2022-01-09 19:58 UTC, LucasNry commented on src/main/java/com/t2g/app/facade/YTAPIFacade.java
> +        for (Song song: songs) {
Fazer uma request de adição por música vai fazer com que tomemos throttling da API do YouTube, principalmente por estarmos usando o free tier. Não tem um endpoint pra adicionar em batches? Ou será que você não consegue adicionar mais de uma música por esse endpoint mesmo?

2022-01-09 20:02 UTC, LucasNry commented on src/main/java/com/t2g/app/facade/YTAPIFacade.java
> +        JsonObject jsonResponse = getJsonResponse(endpoint);
Um dos problemas que tive na hora de pegar a playlist foram limites de música por request. Testei uma playlist de mais de 1000 músicas e somente 100 vinham, existia uma maneira de pegar todas mas precisava de mais requests. Consegue testar com uma playlist grande (mais de 200 músicas pelo menos) pra ver se o yt n tem essa mesma limitação?

2022-01-09 20:03 UTC, LucasNry requested changes
Deixei alguns comentários pra vc dar uma olhada

2022-01-09 21:15 UTC, heywtl commented on src/main/java/com/t2g/app/facade/YTAPIFacade.java
> +        JsonObject jsonResponse = getJsonResponse(endpoint);
o YouTube só retorna no máximo 50 músicas de uma playlist por request, teria também que fazer mais requests, por isso acabei deixando assim, já que já ta bem custoso dessa forma

2022-01-09 21:19 UTC, heywtl commented on src/main/java/com/t2g/app/facade/YTAPIFacade.java
> +        for (Song song: songs) {
pelo menos na descrição da api do youtube não tem nada descrevendo uma forma de adicionar mais de um resource em uma playlist, teria que ser uma por uma mesmo

2022-01-10 23:14 UTC, LucasNry approved these changes

2022-01-10 23:14 UTC, merged